services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    depends_on:
      - mssql
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password1-"
    volumes:
      - cinema-together-db:/var/opt/mssql

volumes:
  cinema-together-db: